parameters:
  - name: environment
    type: string
  - name: functionAppName
    type: string
  - name: azureSubscription
    type: string
  - name: resourceGroupName
    type: string
  - name: slotName
    type: string


steps:
  - task: AzureAppServiceSettings@1
    displayName: 'Configure Function App Settings'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      appName: ${{ parameters.functionAppName }}
      resourceGroupName: ${{ parameters.resourceGroupName }}
      slotName: ${{ parameters.slotName }}
      appSettings: |
        [
          { 
            "name": "Reports__TransferMaterial__Enabled",
            "value": "$(TransferMaterialEnabled)",
            "slotSetting": false
          },
          { 
            "name": "Reports__TransferMaterial__CronSchedule",
            "value": "$(TransferMaterialCronSchedule)",
            "slotSetting": false
          },
          { 
            "name": "Reports__TransferMaterial__WorkspaceId",
            "value": "$(ApplicationInsightsWorkspaceId)",
            "slotSetting": false
          },
          { 
            "name": "Reports__TransferMaterial__TimeRangeDays",
            "value": "$(TransferMaterialTimeRangeDays)",
            "slotSetting": false
          },
          { 
            "name": "Reports__TransferMaterial__StorageContainer",
            "value": "lcc-reports-${{ parameters.environment }}",
            "slotSetting": false
          },
          { 
            "name": "Reports__TransferMaterial__StoragePath",
            "value": "$(TransferMaterialStoragePath)",
            "slotSetting": false
          },
          { 
            "name": "BlobStorageAccountUrl",
            "value": "$(BlobStorageAccountUrl)",
            "slotSetting": false
          },
          {
            "name": "FUNCTIONS_EXTENSION_VERSION",
            "value": "~4",
            "slotSetting": false
          },
          {
            "name": "FUNCTIONS_WORKER_RUNTIME",
            "value": "dotnet-isolated",
            "slotSetting": false
          },
          {
            "name": "DOTNET_FRAMEWORK_VERSION",
            "value": "v10.0",
            "slotSetting": false
          },
          {
            "name": "WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED",
            "value": "1",
            "slotSetting": false
          },
          {
            "name": "WEBSITE_RUN_FROM_PACKAGE",
            "value": "1",
            "slotSetting": false
          }
        ]