variables:
- name: TransferMaterialEnabled
  value: "true"
- name: TransferMaterialCronSchedule
  value: "0 0 0 * * *"
- name: TransferMaterialTimeRangeDays
  value: "1.0"
- name: TransferMaterialStoragePath
  value: "transfer-material"
